language: ruby
rvm:
  - "1.9.3"
before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - export DISCOURSE_HOSTNAME=www.example.com
  - export RUBY_GC_MALLOC_LIMIT=50000000
  - rake db:migrate
bundler_args: --without development
script: 'bundle exec rspec && bundle exec rake qunit:test'
services:
  - redis-server
